apiVersion: v1
kind: Namespace
metadata:
  name: elice-devops-stg
  labels:
    name: elice-devops-stg
    environment: staging
    managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"