apiVersion: v1
kind: Namespace
metadata:
  name: elice-devops-prod
  labels:
    name: elice-devops-prod
    environment: production
    managed-by: argocd
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    argocd.argoproj.io/sync-wave: "-1"